# Generated by Django 3.1.5 on 2021-03-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='isComplete',
            new_name='is_complete',
        ),
    ]
